# Generated by Django 2.1.7 on 2019-05-04 19:04

import classtagram.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=15)),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('is_student', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', classtagram.models.UserManager()),
            ],
        ),
    ]
