# Generated by Django 2.1.7 on 2019-05-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classtagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
    ]
