export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const MAIN_INFO = 'MAIN_INFO';
export const MAIN_INFO_SUCCESS = 'MAIN_INFO_SUCCESS';
export const MAIN_INFO_ERROR = 'MAIN_INFO_ERROR';

export const COURSE_INFO = 'COURSE_INFO';
export const COURSE_INFO_SUCCESS = 'COURSE_INFO_SUCCESS';
export const COURSE_INFO_ERROR = 'COURSE_INFO_ERROR';

export const PHOTO_POST = 'PHOTO_POST';
export const PHOTO_POST_SUCCESS = 'PHOTO_POST_SUCCESS';
export const PHOTO_POST_ERROR = 'PHOTO_POST_ERROR';

export const PHOTO_COURSE_INFO = 'PHOTO_COURSE_INFO';
export const PHOTO_COURSE_INFO_SUCCESS = 'PHOTO_COURSE_INFO_SUCCESS';
export const PHOTO_COURSE_INFO_ERROR = 'PHOTO_COURSE_INFO_ERROR';

export const PHOTO_INFO = 'PHOTO_INFO';
export const PHOTO_INFO_SUCCESS = 'PHOTO_INFO_SUCCESS';
export const PHOTO_INFO_ERROR = 'PHOTO_INFO_ERROR';

export const TAG_POST = 'TAG_POST';
export const TAG_POST_SUCCESS = 'TAG_POST_SUCCESS';
export const TAG_POST_ERROR = 'TAG_POST_ERROR';

export const TAG_PUT = 'TAG_PUT';
export const TAG_PUT_SUCCESS = 'TAG_PUT_SUCCESS';
export const TAG_PUT_ERROR = 'TAG_PUT_ERROR';

export const TAG_PHOTO_INFO = 'TAG_PHOTO_INFO';
export const TAG_PHOTO_INFO_SUCCESS = 'TAG_PHOTO_INFO_SUCCESS';
export const TAG_PHOTO_INFO_ERROR = 'TAG_PHOTO_INFO_ERROR';